### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by callumbnz** [benmaddison/prngmgr#3]
Really like the idea of it - is it still maintained?

**Comment by benmaddison** [comment]
yes it is, although i haven't had a chance to get much work on it done recently. hoping to get some substantial work done in time to showcase at GPF this year.

**Comment by callumbnz** [comment]
Awesome. I managed to get it installed and working. So that's a bonus.

We are a juniper shop, so the snmp stuff will require a bit of re-working.
Shall see how I go :)
